name: Call webhook remote

on:
  schedule:
  - cron: "0 2 * * *" # Runs at 02:00 UTC everyday
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2.3.4

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt

      - name: Execute Python script # Run the webhook_remote.py script
        run: python webhook_remote.py